/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as PathlessLayoutSearchRouteImport } from './routes/_pathlessLayout/search'
import { Route as PathlessLayoutPageRouteImport } from './routes/_pathlessLayout/$page'
import { Route as PathlessLayoutItemIdRouteImport } from './routes/_pathlessLayout/item/$id'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutSearchRoute = PathlessLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutPageRoute = PathlessLayoutPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutItemIdRoute = PathlessLayoutItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PathlessLayoutIndexRoute
  '/health': typeof HealthRoute
  '/$page': typeof PathlessLayoutPageRoute
  '/search': typeof PathlessLayoutSearchRoute
  '/api/inngest': typeof ApiInngestRoute
  '/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/$page': typeof PathlessLayoutPageRoute
  '/search': typeof PathlessLayoutSearchRoute
  '/api/inngest': typeof ApiInngestRoute
  '/': typeof PathlessLayoutIndexRoute
  '/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/_pathlessLayout/$page': typeof PathlessLayoutPageRoute
  '/_pathlessLayout/search': typeof PathlessLayoutSearchRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/$page'
    | '/search'
    | '/api/inngest'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/health' | '/$page' | '/search' | '/api/inngest' | '/' | '/item/$id'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/health'
    | '/_pathlessLayout/$page'
    | '/_pathlessLayout/search'
    | '/api/inngest'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  ApiInngestRoute: typeof ApiInngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/search': {
      id: '/_pathlessLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PathlessLayoutSearchRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/$page': {
      id: '/_pathlessLayout/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PathlessLayoutPageRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/item/$id': {
      id: '/_pathlessLayout/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof PathlessLayoutItemIdRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutPageRoute: typeof PathlessLayoutPageRoute
  PathlessLayoutSearchRoute: typeof PathlessLayoutSearchRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutItemIdRoute: typeof PathlessLayoutItemIdRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutPageRoute: PathlessLayoutPageRoute,
  PathlessLayoutSearchRoute: PathlessLayoutSearchRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutItemIdRoute: PathlessLayoutItemIdRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  ApiInngestRoute: ApiInngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
