/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutSearchRouteImport } from './routes/_pathlessLayout/search'
import { Route as PathlessLayoutPageRouteImport } from './routes/_pathlessLayout/$page'
import { Route as PathlessLayoutItemIdRouteImport } from './routes/_pathlessLayout/item/$id'

const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutSearchRoute = PathlessLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutPageRoute = PathlessLayoutPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutItemIdRoute = PathlessLayoutItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$page': typeof PathlessLayoutPageRoute
  '/search': typeof PathlessLayoutSearchRoute
  '/': typeof PathlessLayoutIndexRoute
  '/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRoutesByTo {
  '/$page': typeof PathlessLayoutPageRoute
  '/search': typeof PathlessLayoutSearchRoute
  '/': typeof PathlessLayoutIndexRoute
  '/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/_pathlessLayout/$page': typeof PathlessLayoutPageRoute
  '/_pathlessLayout/search': typeof PathlessLayoutSearchRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/item/$id': typeof PathlessLayoutItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$page' | '/search' | '/' | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$page' | '/search' | '/' | '/item/$id'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/$page'
    | '/_pathlessLayout/search'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/search': {
      id: '/_pathlessLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PathlessLayoutSearchRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/$page': {
      id: '/_pathlessLayout/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PathlessLayoutPageRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/item/$id': {
      id: '/_pathlessLayout/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof PathlessLayoutItemIdRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutPageRoute: typeof PathlessLayoutPageRoute
  PathlessLayoutSearchRoute: typeof PathlessLayoutSearchRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutItemIdRoute: typeof PathlessLayoutItemIdRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutPageRoute: PathlessLayoutPageRoute,
  PathlessLayoutSearchRoute: PathlessLayoutSearchRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutItemIdRoute: PathlessLayoutItemIdRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
